name: Docker Build

on: push

jobs:
  build:
    name: Build (${{ matrix.name }}-${{ matrix.wordpress_version }}-php${{ matrix.php_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: []
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/clevyr/${{ matrix.name }}-wordpress
          tags: |
            type=raw,value=${{ matrix.wordpress_version }}-php${{ matrix.php_version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          pull: true
          push: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            WORDPRESS_VERSION=${{ matrix.wordpress_version }}
            PHP_VERSION=${{ matrix.php_version }}
            PHP_EXTENSIONS=${{ matrix.php_extensions }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
