name: Docker Build

on: push

jobs:
  build:
    name: Build (${{ matrix.wordpress_version }}-php${{ matrix.php_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - wordpress_version: 6.7.2
            php_version: 8.4
            cli_version: 2.11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/clevyr/wordpress
          tags: |
            type=raw,value=${{ matrix.wordpress_version }}-php${{ matrix.php_version }},enabled=${{ matrix.name == '' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          pull: true
          push: ${{ github.ref_name == 'main' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            WORDPRESS_VERSION=${{ matrix.wordpress_version }}
            CLI_VERSION=${{ matrix.cli_version }}
            PHP_VERSION=${{ matrix.php_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
